### ISSUE TITLE
Decimal(17,0) PK/FK result in EF decimal(18,2) and then throw 'Arithmetic overflow' error - is there a way to map to bigint?

### ISSUE THREAD

**Issue by NaomiN** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#129]
Hi Simon,

I posted the exact problem here https://social.msdn.microsoft.com/Forums/sqlserver/en-US/c4295054-e519-4fea-9892-54c0d9a4f2b2/decimal-column-and-entity-framework?forum=sqldataaccess

Our PK columns defined as decimal(17,0).  The auto-generated configuration for the table is

`namespace Siriusware.Data
{
    using Siriusware.Models;
    using System;

```
// sp_log
public partial class SpLogConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SpLog>
{
    public SpLogConfiguration()
        : this("dbo")
    {
    }

    public SpLogConfiguration(string schema)
    {
        ToTable(schema + ".sp_log");
        HasKey(x => x.LogNo);

        Property(x => x.LogNo).HasColumnName("log_no").IsRequired().HasColumnType("numeric").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
        Property(x => x.ActivType).HasColumnName("activ_type").IsRequired().HasColumnType("int");
        Property(x => x.TagLine).HasColumnName("tag_line").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(120);
        Property(x => x.Details).HasColumnName("details").IsRequired().IsUnicode(false).HasColumnType("text").HasMaxLength(2147483647);
        Property(x => x.Sourceapp).HasColumnName("sourceapp").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(20);
        Property(x => x.@Operator).HasColumnName("operator").IsRequired().IsFixedLength().IsUnicode(false).HasColumnType("char").HasMaxLength(6);
        Property(x => x.Salespoint).HasColumnName("salespoint").IsRequired().IsFixedLength().IsUnicode(false).HasColumnType("char").HasMaxLength(6);
        Property(x => x.DateTime).HasColumnName("date_time").IsOptional().HasColumnType("datetime");
        InitializePartial();
    }
    partial void InitializePartial();
}
```

}
// </auto-generated>

When EF creates the INSERT command, it uses decimal(18,2) instead of decimal(17,0) or bigint. And while this select cast(3438000001.00 as  decimal(17,0)) works, when I tried double cast from decimal(18,2) to decimal(17,0) I got this 'Arithmetic overflow' error.

Do you see what solution we can implement to solve the problem?

Thanks in advance.`

**Comment by NaomiN** [comment]
Apparently the select cast problem is reproducible only in my DB - very strange error indeed. There is no corruption with DBCC CHECKDB test.

So, while it seems helpful to define parameters precision and scale, the issue may not be too pressing.

**Comment by sjh37** [comment]
Perhaps your DB is slightly different. Perhaps you have not saved the tt file to regenerate the configuration to map to your database. The last bit is a bad idea if its working in qa/production, which points to your db not being quite right.

Take a look at the DDL for your sp_log table to see if it matches your other colleages. Alternatively, take a backup from a server that works ok, and restore it onto your pc.

Run the following to see the typename, previsiona and scale to see what you get

``` sql
SELECT  c.TABLE_SCHEMA AS SchemaName,
        c.TABLE_NAME AS TableName,
        t.TABLE_TYPE AS TableType,
        c.ORDINAL_POSITION AS Ordinal,
        c.COLUMN_NAME AS ColumnName,
        CAST(CASE WHEN IS_NULLABLE = 'YES' THEN 1
                  ELSE 0
             END AS BIT) AS IsNullable,
        DATA_TYPE AS TypeName,
        ISNULL(CHARACTER_MAXIMUM_LENGTH, 0) AS [MaxLength],
        CAST(ISNULL(NUMERIC_PRECISION, 0) AS INT) AS [Precision],
        ISNULL(COLUMN_DEFAULT, '') AS [Default],
        CAST(ISNULL(DATETIME_PRECISION, 0) AS INT) AS DateTimePrecision,
        ISNULL(NUMERIC_SCALE, 0) AS Scale,
        CAST(COLUMNPROPERTY(OBJECT_ID(QUOTENAME(c.TABLE_SCHEMA) + '.' + QUOTENAME(c.TABLE_NAME)), c.COLUMN_NAME, 'IsIdentity') AS BIT) AS IsIdentity,
        CAST(CASE WHEN COLUMNPROPERTY(OBJECT_ID(QUOTENAME(c.TABLE_SCHEMA) + '.' + QUOTENAME(c.TABLE_NAME)), c.COLUMN_NAME, 'IsIdentity') = 1 THEN 1
                  WHEN COLUMNPROPERTY(OBJECT_ID(QUOTENAME(c.TABLE_SCHEMA) + '.' + QUOTENAME(c.TABLE_NAME)), c.COLUMN_NAME, 'IsComputed') = 1 THEN 1
                  WHEN DATA_TYPE = 'TIMESTAMP' THEN 1
                  WHEN DATA_TYPE = 'UNIQUEIDENTIFIER' AND LOWER(ISNULL(COLUMN_DEFAULT, '')) LIKE '%newsequentialid%' THEN 1
                  ELSE 0
             END AS BIT) AS IsStoreGenerated,
        CAST(CASE WHEN pk.ORDINAL_POSITION IS NULL THEN 0
                  ELSE 1
             END AS BIT) AS PrimaryKey,
        ISNULL(pk.ORDINAL_POSITION, 0) PrimaryKeyOrdinal,
        CAST(CASE WHEN fk.COLUMN_NAME IS NULL THEN 0
                  ELSE 1
             END AS BIT) AS IsForeignKey
FROM    INFORMATION_SCHEMA.COLUMNS c
        INNER JOIN INFORMATION_SCHEMA.TABLES t
            ON c.TABLE_SCHEMA = t.TABLE_SCHEMA
               AND c.TABLE_NAME = t.TABLE_NAME
        LEFT OUTER JOIN (SELECT u.TABLE_SCHEMA,
                                u.TABLE_NAME,
                                u.COLUMN_NAME,
                                u.ORDINAL_POSITION
                         FROM   INFORMATION_SCHEMA.KEY_COLUMN_USAGE u
                                INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
                                    ON u.TABLE_SCHEMA = tc.CONSTRAINT_SCHEMA
                                       AND u.TABLE_NAME = tc.TABLE_NAME
                                       AND u.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
                         WHERE  CONSTRAINT_TYPE = 'PRIMARY KEY') pk
            ON c.TABLE_SCHEMA = pk.TABLE_SCHEMA
               AND c.TABLE_NAME = pk.TABLE_NAME
               AND c.COLUMN_NAME = pk.COLUMN_NAME
        LEFT OUTER JOIN (SELECT DISTINCT
                                u.TABLE_SCHEMA,
                                u.TABLE_NAME,
                                u.COLUMN_NAME
                         FROM   INFORMATION_SCHEMA.KEY_COLUMN_USAGE u
                                INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
                                    ON u.TABLE_SCHEMA = tc.CONSTRAINT_SCHEMA
                                       AND u.TABLE_NAME = tc.TABLE_NAME
                                       AND u.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
                         WHERE  CONSTRAINT_TYPE = 'FOREIGN KEY') fk
            ON c.TABLE_SCHEMA = fk.TABLE_SCHEMA
               AND c.TABLE_NAME = fk.TABLE_NAME
               AND c.COLUMN_NAME = fk.COLUMN_NAME
WHERE c.TABLE_NAME NOT IN ('EdmMetadata', '__MigrationHistory')
and c.TABLE_NAME = 'sp_log'
```

**Comment by NaomiN** [comment]
Hi Simon,

There was really weird problem in my DB (I documented it here https://social.msdn.microsoft.com/Forums/sqlserver/en-US/af8b3938-3a6d-4dbc-935e-7c409093449f/select-cast200000100-as-decimal170-works-in-compatibility-level-2012-and-throws-error-in?forum=transactsql

To me the problem sounded extremely weird. Only one particular DB exhibited this problem. At the end I just took the same DB from my colleague instead of my own "corrupted" and the problem thus was resolved. I still think it would be nice to allow configuration files to specify exact scale and precision for decimal columns, I checked Fluent API documentation but didn't see how exactly it could be done. I think it could be done, though, I probably just missed it.

See, if you think you can implement the scale and precision into configuration files. Also, as a possibility, if, say, the column is decimal (17,0) it can be mapped to bigint.

Thanks in advance.

**Comment by NaomiN** [comment]
Apparently, it's just .HasPrecision(17,0) in the Fluent API. I'll review my configuration files, but I think it should be added if it's not done already (we're few versions behind, I think).

See https://social.msdn.microsoft.com/Forums/en-US/c4295054-e519-4fea-9892-54c0d9a4f2b2/decimal-column-and-entity-framework?forum=adodotnetentityframework

In our current configurations we have

Property(x => x.Masterpass).HasColumnName("masterpass").IsRequired().HasColumnType("numeric");

Here it could have been also specified precision. Was there already an enhancement?

Our version is // v2.19.0

**Comment by sjh37** [comment]
Currently, it's set as

``` c#
(Scale > 0) ? ".HasPrecision(" + Precision + "," + Scale + ")" : string.Empty,
```

In this case the scale is zero, so won't get added. I will fix it.

**Comment by sjh37** [comment]
Done. This will be in the next release.
if you want this now, alter the line above to be:

``` c#
(Precision > 0 || Scale > 0) ? ".HasPrecision(" + Precision + "," + Scale + ")" : string.Empty,
```

**Comment by NaomiN** [comment]
Thanks, Simon! I think we can wait. Is there a way to get a list of changes from the version we're using v2.19.0 and the next release? We haven't yet upgraded as it may be a hassle for us, but will look into upgrading.

BTW, I started to watch the Pluralsight course and love it.

**Comment by sjh37** [comment]
List of changes are [here](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/What's-New).

**Comment by NaomiN** [comment]
I am not clear as how to update. From VS Tools/Extensions & Updates I found that Reverse POCO needed an Update. I selected to proceed, the installer worked, I see no longer the 'Update' but I see no difference. The ttinclude files still show version 2.19.0

**Comment by arbh89** [comment]
Hi @NaomiN, you must delete the files and add them again in order to get the latest updated files.

**Comment by NaomiN** [comment]
Do you mean delete all ttinclude files including our own?

**Comment by sjh37** [comment]
It updated the reverse generator template within Visual Studio, but NOT YOUR PROJECT.
You must re-add the generator to your project, then you will get the new version.
Updating extensions never touches your code or your project.

**Comment by NaomiN** [comment]
Thanks, I will have to check documentation as how to do that (or view the Pluralsight course that part again). I also probably will wait till the next version that will include the precision fix.
